### ISSUE TITLE
help please unrecognized flag '-Os' in 'p2' in visual c++ 2017 

### ISSUE THREAD

**Issue by ayassinsayed** [martinrotter/qt5-minimalistic-builds#10]
hello 
please help me to solve this issues i use qt static relase   qt-5.10.1-static-ltcg-msvc2017-x86_64.7z
and in visual studio 2017 i use /LTCG option but i face " error unrecognized flag '-Os' in 'p2' " when compile any code

**Comment by martinrotter** [comment]
1. Make sure you really downloaded "qt-5.10.1-static-ltcg-msvc2017-x86_64.7z".
2. Try to switch off optimizations in your VS project settings.

![image](https://user-images.githubusercontent.com/1255302/48183191-2bf0c400-e32e-11e8-8c2a-17825e7ee3df.png)

**Comment by ayassinsayed** [comment]
finally it work , Thanks for help i just update visual studio to 15.8 and change config to your mention solution in above post and error has gone , but i have another problem when i compile any code give me error unresolved external symbol you can see in picture below !??? another Question please is "qt-5.10.1-static-ltcg-msvc2017-x86_64.7z"   x64 only or  x86 i see in solution platform only x64 bit how i can change platform to x86  ??? Thanks for your time to help me 
![capture](https://user-images.githubusercontent.com/35578089/48237525-ab829f80-e3cf-11e8-823d-2ad3083a5332.PNG)

**Comment by martinrotter** [comment]
These libraries are x64 only as stated in readme.

`these binaries are compiled with MinGW-w64 or MSVC2017 toolchain and are x64,`

**Comment by ayassinsayed** [comment]
Thanks i see that **But,** **when i compile any code give me error unresolved external symbol you can see in picture below what is library i missing** or what is the problem and why qt-vsaddin-msvc2017 not add that library automatically like standard QT Dynamic Release ??? Thanks for your time 
![48237525-ab829f80-e3cf-11e8-823d-2ad3083a5332](https://user-images.githubusercontent.com/35578089/48260744-48bbf300-e425-11e8-8d42-1d4257acf0d5.PNG)
