### ISSUE TITLE
Static build, openssl for 5.12.2

### ISSUE THREAD

**Issue by yalov** [martinrotter/qt5-minimalistic-builds#12]
I failed to compile static Qt 5.12(.2) LTS, msvc x64 (or x86)

`ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed.`

There was some relative changes https://bugreports.qt.io/browse/QTBUG-73205, but I can figure this out

Do you know how to update the script?

**Comment by martinrotter** [comment]
First, you need to statically build openssl-1.1 and then update script accordingly.

**Comment by martinrotter** [comment]
I will compile static Qt for you soon.
