### ISSUE TITLE
Mismatch RunttimeLibrary when compiling statically

### ISSUE THREAD

**Issue by Akandesh** [martinrotter/qt5-minimalistic-builds#14]
![devenv_T7jPdQcjAj](https://user-images.githubusercontent.com/22220362/91638128-7bc1e300-ea0d-11ea-8b58-0b795ba1834f.png)

After putting the files in C:\qtb\qt-5.12.9-static-msvc2019-x86_64 and setting the Qt plugin to use that in project settings and setting code generation to /MT I was met with these errors. Why?

**Comment by Akandesh** [comment]
Managed to build it myself using https://github.com/fpoussin/Qt5-MSVC-Static /shrug

**Comment by martinrotter** [comment]
Probably due to /MT /MD mismatch.
