### ISSUE TITLE
Cannot compile QWT

### ISSUE THREAD

**Issue by Mercury13** [martinrotter/qt5-minimalistic-builds#2]
Cannot compile QWT with MinGW-w64 prebuilt 5.10.0. Writes lots of errors like:

c:\Qt\qwt-6.1.3\src/qwt_abstract_scale_draw.cpp:171: undefined reference to `_imp___ZN8QPainter4saveEv'

There are functions with 1 underscore less in libraries, e.g. _imp__ZN8QPainter4saveEv.
Tested with MinGW-w64 5.3 to 7.1.

Also -Wa,-mbig-obj key is redundant in x64 MinGW, I was forced to remove it.

**Comment by martinrotter** [comment]
I compiled Qwt 6.1.3 with MinGW-w64 (dynamic) and MSVC2017 (static and dynamic) prebuilt Qt without problems.

https://gist.github.com/7e5f9d101f6dd6ece2c87378f0fc2e8e

**Comment by martinrotter** [comment]
Therefore this does not seem to be the problem with prebuilt Qt libs.

**Comment by Mercury13** [comment]
Then what am I doing wrong?
Cannot compile QWT with your Qt. Cannot compile Qt for myself. Also tested with MSYS (g++ 7.3.0).

**Comment by martinrotter** [comment]
I compiled with Qt Creator. I can upload compiled libs if you want?

**Comment by martinrotter** [comment]
Also, did you run  `qtbinpatcher.exe`?

**Comment by martinrotter** [comment]
Also do you try static build or dynamic build?

**Comment by Mercury13** [comment]
Run. Dynamic. Compiling using Qt Creator really helped, but it was something interesting.
I gagged all errors and most warnings in my project (except fallthrough — I don’t know how to tell that it’s legitimate, nothing helps), and working with dependencies right now.

error: skipping incompatible C:\Mercury\Common\cURL\lib/libcurldll.a when searching for -lcurldll

That’s understandable, I did not upgrade cURL. But one of errors is extremely strange.

error: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libqwt.dll.a when searching for -lqwt

WHAT? I’ve just compiled QWT, and Dependency Walker shows that qwt.dll is x64.

**Comment by martinrotter** [comment]
So all if fine now?

**Comment by Mercury13** [comment]
No, I don’t understand why the library is incompatible.

**Comment by martinrotter** [comment]
Wait, you wrote 

>  I’ve just compiled QWT, and Dependency Walker shows that qwt.dll is x64.

So did you compiled Qwt with my prebuilt Qt or not? I am very confused. What is `my project`? How `curl` comes into this?

**Comment by Mercury13** [comment]
Strange, but I recompiled, and everything helped.
