### ISSUE TITLE
Old Win2K style under Windows 8

### ISSUE THREAD

**Issue by Mercury13** [martinrotter/qt5-minimalistic-builds#3]
Adding/changing/removing XP theme manifest using XN Resource Editor does not help.

**Comment by Mercury13** [comment]
![image](https://user-images.githubusercontent.com/10164882/36853653-b239a5cc-1d77-11e8-8df7-cde1b9b5c73a.png)
![screen10](https://user-images.githubusercontent.com/10164882/36853742-e6c082b6-1d77-11e8-92f9-f0cda4b69434.png)
![image 1](https://user-images.githubusercontent.com/10164882/36853938-6b65d25a-1d78-11e8-85e4-35c235479814.png)

**Comment by Mercury13** [comment]
Don’t look at jaggy Win10 fonts, that’s how my work machine is set up. Look at style: 1 is bad, 2 and 3 are OK.

**Comment by martinrotter** [comment]
Tested on Win 8 in virtual box. All works.

http://doc.qt.io/qt-5/qapplication.html#setStyle-1

`QApplication::setStyle("windowsvista");`

**Comment by Mercury13** [comment]
Is “windowsvista” a simulation or a true OS style?

**Comment by Mercury13** [comment]
setStyle() does not help.

**Comment by Mercury13** [comment]
Closing the issue, it relates to the entire 5.10 branch.

**Comment by martinrotter** [comment]
Wait so is this upstream Qt bug?

**Comment by Mercury13** [comment]
Yes, this is a bug of Qt 5.10, repeated in “official” x86 build.
Moved to self-compiled Qt 5.9.3 right now.

**Comment by Mercury13** [comment]
(5.9.4 has a bug in build script recognized officially)
