### ISSUE TITLE
Static x32 (MinGW or MSVC)

### ISSUE THREAD

**Issue by yalov** [martinrotter/qt5-minimalistic-builds#4]
Request Static MinGW x32 version

**Comment by yalov** [comment]
In `build5101msvc.ps1` I see  `-platform win32-msvc2017`, it looks pretty x32 for me. 
Will I get x32 static Qt, if I change openssl libs to x32 ?

**Comment by martinrotter** [comment]
That file is for building MSVC version of Qt, not MinGW. Moreover, `win32-msvc2017` is [qmakespec](http://doc.qt.io/qt-5/qmake-environment-reference.html#qmakespec) option. Although its name contains `32`, it has nothing to do with type (`x86/x64`) of built libraries, those are decided by used compiler.

x86 architecture is declining and its usage is decreasing rapidly. We will see if there will be more requests for this, right now, I do not have time resources for building also x86 variants of Qt, as I myself use only x64 variants.

**Comment by martinrotter** [comment]
That said, you can use script `build510static.sh` to build what you want, proably you do not have to modify anything:

1. Install x86 MSYS2.
2. Navigate to git repo root folder.
3. Run the script. (in Bash)

I can try myself, but I really cannot promise anything.

**Comment by yalov** [comment]
I have 
`ERROR: Feature 'dbus-linked' was enabled, but the pre-condition 'features.dbus && libs.dbus' failed.`
How I can fix that for MSYS2 on Windows?

**Comment by martinrotter** [comment]
Do you have `mingw-w64-x86-dbus` installed?

**Comment by yalov** [comment]
```
$ pacman -S mingw-w64-i686-dbus
//ok

$ which mingw-w64-x86-dbus
which: no mingw-w64-x86-dbus in (/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

**Comment by yalov** [comment]
ok, I compiled qt 5.10.0 msvc x86 static.


What about mingw x86? Is mingw-w64-x86-dbus correctly installed?

**Comment by martinrotter** [comment]
Looks like it is. I will try to compile tomorrow and upload it.

**Comment by martinrotter** [comment]
Feel free to cleanup your script a bit and pull request it to here. I also polished other scripts a bit.

**Comment by yalov** [comment]
I just remove all x64 staff, and change openssl so no need to PR.

BTW, I succeed in loading release to github using MS Edge. (also had had problem with Chrome, if that the reason why you loads it to bitbucket)
https://github.com/yalov/qt5-minimalistic-builds-x86/releases
