### ISSUE TITLE
Will support qt lite

### ISSUE THREAD

**Issue by MetalKingdom** [martinrotter/qt5-minimalistic-builds#6]
Do you will support qt lite with the new updates
could you add it

**Comment by martinrotter** [comment]
What si "qt lite"?

**Comment by martinrotter** [comment]
If you mean [this](http://blog.qt.io/blog/2017/05/31/qt-lite-qt-5-9-lts/), then these my Qt builds are already "lite". Check [releases](https://github.com/martinrotter/qt5-minimalistic-builds/releases), they have almost all optional switches turned OFF, which results in LESS dependencies and smaller Qt libraries.

If you have some recommendations on further build options which could be used, give it here.
