### ISSUE TITLE
can not create new project with vs2017

### ISSUE THREAD

**Issue by nie11kun** [martinrotter/qt5-minimalistic-builds#7]
hi, i am looking for the prebuilded QT for a while, thanks for your work.
for some reason, i need static library, i tried build form source but failed anyway.
my enviorment is windows10 x64 pro with last vs2017, i write c++ console applications before.

i download 5.10.1 static library from your site and executed qtbinpatcher.exe. QT VS tool installed and QT option set the right path.

when create a new QTguiappliation with default settings,
last step while show an error: **object reference not set to an instance of an object qt**

any suggestions for me？ thanks.

**Comment by martinrotter** [comment]
Can you share ZIPPED version of your application you are trying to compile?

**Comment by nie11kun** [comment]
you mean the version i downloaded? 
this one: qt-5.10.1-static-ltcg-msvc2017-x86_64.7z
my windows 10 SDK version is 10.0.17134.0

**Comment by martinrotter** [comment]
Nono, just upload the sample Qt application which gave you the error, I will try to compile myself.

**Comment by nie11kun** [comment]
Actually, i will encounter this error when create the new application with qtguiapplication. Application failed to create.
