### ISSUE TITLE
Add Qt 5.11.2 static build for VS 2017

### ISSUE THREAD

**Issue by jcfr** [martinrotter/qt5-minimalistic-builds#9]
First, thanks for sharing these scripts :+1: 

Here is a topic allowing to build Qt 5.11.2 statically (this one is for 32-bit with openssl disabled): https://github.com/jcfr/qt5-minimalistic-builds/tree/add-msvc-build5112-static-x86

If there is interest in accepting the contributions, I could also improve the existing script `msvc-build5112.ps1` to accept options like `-static`, `static-openssl`, `without-openssl`, ...

**Comment by martinrotter** [comment]
Hello.

I prefer to keep scripts for static/non-static builds of each Qt version separate. Anyway, I will compile static build next week or maybe today, we will see. Dynamic build is already there: https://bitbucket.org/skunkos/qt5-minimalistic-builds/downloads/

Feel free to make any pull requests, but pls keep those files separate, I just like it that way. Thank you. :)
